on: [push]

name: build

jobs:
  build_java_11_jdk_slim_aws:
    name: Build 11 jdk slim aws
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 11-jdk-slim-aws 
      uses: philips-software/docker-ci-scripts@v1.0.1
      with:
        dockerfile: 11/jdk/slim-aws 
        tags: openjdk:11-aws openjdk:11-jdk-aws openjdk:11-jdk-slim-aws openjdk:11.0.6-jdk-slim-aws
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software

  build_java_11_jdk_slim:
    name: Build 11 jdk slim
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 11-jdk-slim 
      uses: philips-software/docker-ci-scripts@v1.0.1
      with:
        dockerfile: 11/jdk/slim 
        tags: openjdk openjdk:11 openjdk:11-jdk openjdk:11-jdk-slim openjdk:11.0.6-jdk-slim
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software

  build_java_11_jdk_zulu:
    name: Build 11 jdk zulu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 11-jdk-zulu 
      uses: philips-software/docker-ci-scripts@v1.0.1
      with:
        dockerfile: 11/jdk/zulu
        tags: openjdk:11-zulu openjdk:11-jdk-zulu openjdk:11-jdk-zulu openjdk:11.0.5-jdk-zulu
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software

  build_java_11_jdk_zulu_docker:
    name: Build 11 jdk zulu docker
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 11-jdk-zulu-docker
      uses: philips-software/docker-ci-scripts@v1.0.1
      with:
        dockerfile: 11/jdk/zulu-docker
        tags: openjdk:11-zulu-docker openjdk:11-jdk-zulu-docker openjdk:11-jdk-zulu-docker openjdk:11.0.5-jdk-zulu-docker
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software

  build_java_11_jre_slim_aws:
    name: Build 11 jre slim aws 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 11-jre-slim-aws 
      uses: philips-software/docker-ci-scripts@v1.0.1
      with:
        dockerfile: 11/jre/slim-aws 
        tags: openjdk:11-jre-aws openjdk:11-jre-slim-aws openjdk:11.0.6-jre-slim-aws
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software

  build_java_11_jre_slim:
    name: Build 11 jre slim 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 11-jre-slim 
      uses: philips-software/docker-ci-scripts@v1.0.1
      with:
        dockerfile: 11/jre/slim
        tags: openjdk:11-jre openjdk:11-jre-slim openjdk:11.0.6-jre-slim
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software

  build_java_8_jdk_alpine:
    name: Build 8 JDK alpine 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 8-jdk-alpine
      uses: philips-software/docker-ci-scripts@v1.0.1
      with:
        dockerfile: 8/jdk/alpine 
        tags: openjdk:8 openjdk:8-jdk openjdk:8-jdk-alpine openjdk:8u201-jdk-alpine openjdk:8u201-jdk-alpine3.9
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software

  build_java_8_jre_alpine:
    name: Build 8 JRE alpine 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 8-jre-alpine 
      uses: philips-software/docker-ci-scripts@v1.0.1
      with:
        dockerfile: 8/jre/alpine 
        tags: openjdk:8-jre openjdk:8-jre-alpine openjdk:8u201-jre-alpine openjdk:8u201-jre-alpine3.9
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software
